name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js + npm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Cypress tests (cypress-mochawesome-reporter will generate the HTML report)
      - name: Run Cypress tests
        run: npx cypress run

      - name: List generated reports
        if: always()
        run: |
          echo "Listing cypress reports directory"
          ls -la
          echo "-- cypress/reports --"
          ls -R cypress/reports || true
          echo "-- cypress/screenshots --"
          ls -R cypress/screenshots || true
          echo "-- cypress/videos --"
          ls -R cypress/videos || true

      # 5️⃣ Upload Mochawesome HTML report as artifact (run even if tests fail)
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/**
          if-no-files-found: warn

      # Optional: Upload screenshots on failure
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Optional: Upload videos
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
